export const ROOT_STACK_SCREENS = {
  tabs: { name: '(tabs)', options: { headerShown: false } },
  onboardingIntro: { name: 'onboarding/index', options: { title: 'Welcome', headerShown: true } },
  onboardingFocus: { name: 'onboarding/focus', options: { title: 'Focus', headerShown: true } },
  onboardingEducation: { name: 'onboarding/education', options: { title: 'Education', headerShown: true } },
  onboardingUsage: { name: 'onboarding/usage', options: { title: 'Usage', headerShown: true } },
  onboardingGoals: { name: 'onboarding/goals', options: { title: 'Goals', headerShown: true } },
  onboardingReview: { name: 'onboarding/review', options: { title: 'Your plan', headerShown: true } },
  projectList: { name: 'project/index', options: { title: 'Projects', headerShown: true } },
  projectCreate: { name: 'project/create', options: { title: 'Create project', headerShown: true } },
  projectDetail: { name: 'project/[projectId]', options: { title: 'Project detail', headerShown: true } },
  projectEdit: { name: 'project/[projectId]/edit', options: { title: 'Edit project', headerShown: true } },
  experimentList: { name: 'experiment/index', options: { title: 'Experiments', headerShown: true } },
  experimentCreate: { name: 'experiment/create', options: { title: 'Create experiment', headerShown: true } },
  experimentDetail: {
    name: 'experiment/[experimentId]',
    options: { title: 'Experiment detail', headerShown: true },
  },
  experimentEdit: {
    name: 'experiment/[experimentId]/edit',
    options: { title: 'Edit experiment', headerShown: true },
  },
  experimentAttachmentViewer: {
    name: 'experiment/attachment-viewer',
    options: { title: 'Attachment viewer', headerShown: true },
  },
  experimentCsvPreview: {
    name: 'experiment/csv-preview',
    options: { title: 'CSV preview', headerShown: true },
  },
  notesList: { name: 'notes/index', options: { title: 'Notes', headerShown: true } },
  notesCreate: { name: 'notes/create', options: { title: 'Create note', headerShown: true } },
  notesDetail: { name: 'notes/[noteId]', options: { title: 'Note detail', headerShown: true } },
  notesEdit: { name: 'notes/[noteId]/edit', options: { title: 'Edit note', headerShown: true } },
  notesTags: { name: 'notes/tags', options: { title: 'Tag browser', headerShown: true } },
  hardwareList: { name: 'hardware/index', options: { title: 'Hardware', headerShown: true } },
  hardwareAdd: { name: 'hardware/add', options: { title: 'Add hardware', headerShown: true } },
  hardwareDetail: {
    name: 'hardware/[hardwareId]',
    options: { title: 'Hardware detail', headerShown: true },
  },
  hardwareEdit: {
    name: 'hardware/[hardwareId]/edit',
    options: { title: 'Edit hardware', headerShown: true },
  },
  profileHome: { name: 'profile/index', options: { title: 'Profile', headerShown: true } },
  profileEdit: { name: 'profile/edit', options: { title: 'Edit profile', headerShown: true } },
  profileAvatar: { name: 'profile/avatar', options: { title: 'Avatar picker', headerShown: true } },
  profileStatistics: {
    name: 'profile/statistics',
    options: { title: 'Account statistics', headerShown: true },
  },
  searchGlobal: { name: 'search/index', options: { title: 'Search', headerShown: true } },
  searchResults: { name: 'search/results', options: { title: 'Search results', headerShown: true } },
  settingsHome: { name: 'settings/index', options: { title: 'Settings', headerShown: true } },
  settingsAppearance: { name: 'settings/appearance', options: { title: 'Appearance', headerShown: true } },
  settingsNotifications: {
    name: 'settings/notifications',
    options: { title: 'Notifications', headerShown: true },
  },
  settingsStorageSync: {
    name: 'settings/storage-sync',
    options: { title: 'Storage & sync', headerShown: true },
  },
  settingsAccount: { name: 'settings/account', options: { title: 'Account', headerShown: true } },
  settingsAbout: { name: 'settings/about', options: { title: 'About', headerShown: true } },
  authSplash: { name: 'auth/splash', options: { headerShown: false } },
  authLogin: { name: 'auth/login', options: { headerShown: false } },
  authSignup: { name: 'auth/signup', options: { title: 'Create account', headerShown: false } },
  authLoginEmail: { name: 'auth/login-email', options: { title: 'Email sign in', headerShown: true } },
  authSignupEmail: { name: 'auth/signup-email', options: { title: 'Email sign up', headerShown: true } },
  authForgotPassword: {
    name: 'auth/forgot-password',
    options: { title: 'Forgot password', headerShown: true },
  },
  authResetPassword: {
    name: 'auth/reset-password',
    options: { title: 'Reset password', headerShown: true },
  },
  authCallback: { name: 'auth/callback', options: { headerShown: false } },
  modal: { name: 'modal', options: { presentation: 'modal', title: 'Modal' } },
} as const;
