export const ROOT_STACK_SCREENS = {
  tabs: { name: '(tabs)', options: { headerShown: false } },
  onboarding: { name: 'onboarding/index', options: { title: 'Welcome', headerShown: true } },
  projectList: { name: 'project/index', options: { title: 'Projects', headerShown: true } },
  projectCreate: { name: 'project/create', options: { title: 'Create project', headerShown: true } },
  projectDetail: { name: 'project/[projectId]', options: { title: 'Project detail', headerShown: true } },
  projectEdit: { name: 'project/[projectId]/edit', options: { title: 'Edit project', headerShown: true } },
  experimentList: { name: 'experiment/index', options: { title: 'Experiments', headerShown: true } },
  experimentCreate: { name: 'experiment/create', options: { title: 'Create experiment', headerShown: true } },
  experimentDetail: {
    name: 'experiment/[experimentId]',
    options: { title: 'Experiment detail', headerShown: true },
  },
  experimentEdit: {
    name: 'experiment/[experimentId]/edit',
    options: { title: 'Edit experiment', headerShown: true },
  },
  experimentAttachmentViewer: {
    name: 'experiment/attachment-viewer',
    options: { title: 'Attachment viewer', headerShown: true },
  },
  experimentCsvPreview: {
    name: 'experiment/csv-preview',
    options: { title: 'CSV preview', headerShown: true },
  },
  notesList: { name: 'notes/index', options: { title: 'Notes', headerShown: true } },
  notesCreate: { name: 'notes/create', options: { title: 'Create note', headerShown: true } },
  notesDetail: { name: 'notes/[noteId]', options: { title: 'Note detail', headerShown: true } },
  notesEdit: { name: 'notes/[noteId]/edit', options: { title: 'Edit note', headerShown: true } },
  notesTags: { name: 'notes/tags', options: { title: 'Tag browser', headerShown: true } },
  hardwareList: { name: 'hardware/index', options: { title: 'Hardware', headerShown: true } },
  hardwareAdd: { name: 'hardware/add', options: { title: 'Add hardware', headerShown: true } },
  hardwareDetail: {
    name: 'hardware/[hardwareId]',
    options: { title: 'Hardware detail', headerShown: true },
  },
  hardwareEdit: {
    name: 'hardware/[hardwareId]/edit',
    options: { title: 'Edit hardware', headerShown: true },
  },
  searchGlobal: { name: 'search/index', options: { title: 'Search', headerShown: true } },
  searchResults: { name: 'search/results', options: { title: 'Search results', headerShown: true } },
  authSplash: { name: 'auth/splash', options: { headerShown: false } },
  authLogin: { name: 'auth/login', options: { headerShown: false } },
  authSignup: { name: 'auth/signup', options: { title: 'Create account', headerShown: true } },
  authForgotPassword: {
    name: 'auth/forgot-password',
    options: { title: 'Forgot password', headerShown: true },
  },
  authResetPassword: {
    name: 'auth/reset-password',
    options: { title: 'Reset password', headerShown: true },
  },
  authCallback: { name: 'auth/callback', options: { headerShown: false } },
  modal: { name: 'modal', options: { presentation: 'modal', title: 'Modal' } },
} as const;
